// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCbg8n8GEx7UaXjgRT5DIpPuO7ozkz00uQ',
    appId: '1:828762601541:web:9f13172a8e02b8045acb2c',
    messagingSenderId: '828762601541',
    projectId: 'expensio-afef7',
    authDomain: 'expensio-afef7.firebaseapp.com',
    storageBucket: 'expensio-afef7.firebasestorage.app',
    measurementId: 'G-B3ZQ43HVDD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDdU4oDjw7XSdoQ20u-Y_lR8Qq8UiIscHU',
    appId: '1:828762601541:android:331157bca93af2ae5acb2c',
    messagingSenderId: '828762601541',
    projectId: 'expensio-afef7',
    storageBucket: 'expensio-afef7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDq2lfEq2cJR8Vk2vY4QNwgloW8M35VHc0',
    appId: '1:828762601541:ios:02cb5b383eba756d5acb2c',
    messagingSenderId: '828762601541',
    projectId: 'expensio-afef7',
    storageBucket: 'expensio-afef7.firebasestorage.app',
    iosBundleId: 'com.example.animationandcharts',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDq2lfEq2cJR8Vk2vY4QNwgloW8M35VHc0',
    appId: '1:828762601541:ios:02cb5b383eba756d5acb2c',
    messagingSenderId: '828762601541',
    projectId: 'expensio-afef7',
    storageBucket: 'expensio-afef7.firebasestorage.app',
    iosBundleId: 'com.example.animationandcharts',
  );

}